const asyncHandler = (requestHandler) => {
  return (req, res, next) => {
    Promise.resolve(requestHandler(req, res, next)).catch((err) => next(err));
  };
};

export { asyncHandler };

// highOrder function (function as parameter)

// const asyncHandler = (fn) => {
//   () => {};
// };

// same as it

// const asyncHandler = (func) => () => {};

// it's try,catch but we use promise

// const asyncHandler = (func) => async (req, res, next) => {
//   try {
//     await func(req, res, next);
//   } catch (error) {
//     res.send(error.code || 500).json({
//       success: false,
//       message: error.message,
//     });
//   }
// };
